// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace animals.Models;

public partial class Animal
{
    public Guid AnimalId { get; set; }

    public string AnimalName { get; set; }

    public int NumberLegs { get; set; }

    public string AnimalLocomotion { get; set; }

    public Guid SpecieId { get; set; }

    public virtual Specie Specie { get; set; }
}