// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace animals.Models;

public partial class Specie
{
    public Guid SpecieId { get; set; }

    public string NameGroup { get; set; }

    public string Detail { get; set; }

    public virtual ICollection<Animal> Animals { get; set; } = new List<Animal>();
}